plugins {
    id 'com.android.application'
}

android {
    namespace 'com.uriel.viacom.beta016'
    compileSdk 35

    defaultConfig {
        applicationId 'com.uriel.viacom.beta016'
        minSdk 26
        targetSdk 35
        versionCode 200
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-nearby:19.5.0'
}

// Native Nearby build trigger for ViaCom 0.2.0
